:PROPERTIES:
:CATEGORY: lsp-rocks
:END:
* install
#+begin_src elisp
(use-package websocket
  :load-path "~/git/emacs-websocket")

(use-package lsp-rocks
  :load-path "~/git/lsp-rocks")
#+end_src

#+RESULTS:
: t

fix ts error
npm run build
chmod +x ./lib/cli.js
reate a py file, switch to python-mode from ts

enable lsp-rock mode
enable company-mode for completion

error 

to restart the sever

lsp-rocks-shutdown
npm run build

then start over

can work with java-mode too

#+begin_src 

receive message => id: ekuzbwon, cmd: init, params: {"project":"/home/thanh/git/lsp-rocks/","language":"python","command":"pyright-langserver","args":["--stdio"],"clientInfo":{"name":"Emacs","version":"GNU Emacs 29.1.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)\n of 2023-08-10"}}
[Error  - 9:58:39 p.m.] /home/thanh/git/lsp-rocks/:python client: couldn't create connection to server.
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Launching server using command pyright-langserver failed. Error: spawn pyright-langserver ENOENT".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Process *lsp-rocks* exited abnormally with code 1
#+end_src

#+begin_src
receive message => id: t9zlyr9k, cmd: init, params: {"project":"/home/thanh/git/lsp-rocks/","language":"python","command":"pyright-langserver","args":["--stdio"],"clientInfo":{"name":"Emacs","version":"GNU Emacs 29.1.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)\n of 2023-08-10"}}
[Error  - 9:50:35 p.m.] /home/thanh/git/lsp-rocks/:python client: couldn't create connection to server.
Launching server using command pyright-langserver failed. Error: spawn pyright-langserver ENOENT
receive message => id: 0yd0y93g, cmd: textDocument/didOpen, params: {"textDocument":{"uri":"file:///home/thanh/git/lsp-rocks/foo.py","languageId":"python","version":0,"text":"print(\"hello\")\n\ndef foo(x, y):\n    return x + y\n\nfoo(2, 3)\n\n"}}
ResponseError: Client is not running
    at LanguageClient.sendNotification (/home/thanh/git/lsp-rocks/lib/client.js:141:35)
    at DidOpenTextDocumentFeature.runWith (/home/thanh/git/lsp-rocks/lib/features/textSynchronization.js:15:28)
    at DidOpenTextDocumentFeature.run (/home/thanh/git/lsp-rocks/lib/features/features.js:28:21)
    at LanguageClient.on (/home/thanh/git/lsp-rocks/lib/client.js:425:50)
    at LspRocks.messageHandler (/home/thanh/git/lsp-rocks/lib/lsp-rocks.js:70:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/home/thanh/git/lsp-rocks/lib/lsp-rocks.js:43:17) {
  code: -32096,
  data: undefined
}
receive message => id: mkvbs6g9, cmd: textDocument/didClose, params: {"textDocument":{"uri":"file:///home/thanh/git/lsp-rocks/foo.py"}}
ResponseError: Client is not running
    at LanguageClient.sendNotification (/home/thanh/git/lsp-rocks/lib/client.js:141:35)
    at DidCloseTextDocumentFeature.runWith (/home/thanh/git/lsp-rocks/lib/features/textSynchronization.js:31:28)
    at DidCloseTextDocumentFeature.run (/home/thanh/git/lsp-rocks/lib/features/features.js:28:21)
    at LanguageClient.on (/home/thanh/git/lsp-rocks/lib/client.js:425:50)
    at LspRocks.messageHandler (/home/thanh/git/lsp-rocks/lib/lsp-rocks.js:70:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/home/thanh/git/lsp-rocks/lib/lsp-rocks.js:43:17) {
  code: -32096,
  data: undefined
}
#+end_src
* interact with the websocket ts client
* in the protocol there is no mention of async communication
the impression is that the response comes back right away

the idea of using request id to make communication between emacs and lsp manager completely async that was first seen in lsp-bridge is the invention outside of lsp protocol. This project also adopted this idea.

can lps-mode do the same? can it create new emacs process to handle this heavy work?

no actually lsp-mode also features this idea
https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L3547
             (id (cl-incf lsp-last-id))
* add symbol highlight 
what it the message?

textDocument/documentHighlight

what is the response, async or not,
** error when no feature handle

receive message => id: 93wbegzf, cmd: textDocument/documentHighlight, params: {"position":{"line":12,"character":1},"textDocument":{"uri":"file:///home/thanh/git/lsp-rocks/foo.py"}}
TypeError: Cannot read properties of undefined (reading 'run')
    at LanguageClient.on (/home/thanh/git/lsp-rocks/lib/client.js:425:49)
    at LspRocks.messageHandler (/home/thanh/git/lsp-rocks/lib/lsp-rocks.js:70:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async WebSocket.<anonymous> (/home/thanh/git/lsp-rocks/lib/lsp-rocks.js:43:17)

* must implement feature and register it here 

[[file:~/git/lsp-rocks/client.ts::this.registerFeature(new HoverFeature(this));]]

follow the hover as guidance
* use lsp highlight on the

yay highlight: 
((:kind 2 :range (:start (:line 2 :character 4) :end (:line 2 :character 7)))
 (:kind 2 :range (:start (:line 5 :character 0) :end (:line 5 :character 3)))
 (:kind 2 :range (:start (:line 7 :character 0) :end (:line 7 :character 3)))
 (:kind 2 :range (:start (:line 9 :character 0) :end (:line 9 :character 3)))
 (:kind 2 :range (:start (:line 10 :character 0) :end (:line 10 :character 3)))
 (:kind 2 :range (:start (:line 11 :character 0) :end (:line 11 :character 3))))

lsp--document-highlight-callback

* we need a hook that get called when the symbol at point changes
lsp-mode use idle call 

perhaps symbol highlight can be an inspiration

* impement lsp code actions 
look at [[file:~/git/lsp-mode/lsp-mode.el::lsp-defun lsp-execute-code-action ((action &as &CodeAction :command? :edit?)][lsp-mode]]
- get code action at point
 request textDocument/codeAction

receive message => id: p3doascl, cmd: textDocument/codeAction, params: {"textDocument":{"uri":"file:///home/thanh/git/lsp-rocks/foo.py"},"range":{"start":{"line":22,"character":16},"end":{"line":22,"character":16}},"context":{"diagnostics":[]}}
TypeError: Cannot read properties of undefined (reading 'run')
    at LanguageClient.on (/home/thanh/git/lsp-rocks/lib/client.js:427:49)
    at LspRocks.messageHandler (/home/thanh/git/lsp-rocks/lib/lsp-rocks.js:70:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async WebSocket.<anonymous> (/home/thanh/git/lsp-rocks/lib/lsp-rocks.js:43:17)

receive message => id: 3nj1kq08, cmd: textDocument/codeAction, params: {"textDocument":{"uri":"file:///home/thanh/git/lsp-rocks/foo.py"},"range":{"start":{"line":28,"character":13},"end":{"line":28,"character":13}},"context":{"diagnostics":[]}}
    
- execute it
- there [[file:client.ts::private _initializeResult: InitializeResult | undefined;][are]]
  
  private _initializeResult: InitializeResult | undefined;

  private _capabilities!: ServerCapabilities;

  that the client knows, it can send to emacs or it can figure out by its own


((:title Change signature for 'foo' :command java.action.applyRefactoringCommand :arguments (changeSignature (:textDocument (:uri file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java) :range (:start (:line 38 :character 21) :end (:line 38 :character 21)) :context (:diagnostics nil)) (:methodIdentifier =app/src\/main\/java=/gradle_scope=/main=/=/gradle_used_by_scope=/main,test=/<javapg{App.java[App~foo~QString; :modifier public :returnType void :methodName foo :parameters ((:type String :name bar :defaultValue  :originalIndex 0)) :exceptions nil))) (:title Inline Method :command java.apply.workspaceEdit :arguments ((:changes nil :documentChanges ((:textDocument (:version :null :uri file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java) :edits ((:range (:start (:line 36 :character 3) :end (:line 40 :character 3)) :newText ))))))) (:title Add Javadoc comment :command java.apply.workspaceEdit :arguments ((:changes nil :documentChanges ((:textDocument (:version :null :uri file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java) :edits ((:range (:start (:line 38 :character 2) :end (:line 38 :character 2)) :newText /**
 * @param bar
 */
))))))) (:title Organize imports :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 5 :character 0) :end (:line 6 :character 0)) :newText )))))) (:title Generate Getters and Setters :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 40 :character 3) :end (:line 40 :character 3)) :newText 

public String getBar() {
	return bar;
}

public void setBar(String bar) {
	this.bar = bar;
})))))) (:title Generate Getters :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 40 :character 3) :end (:line 40 :character 3)) :newText 

public String getBar() {
	return bar;
})))))) (:title Generate Setters :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 40 :character 3) :end (:line 40 :character 3)) :newText 

public void setBar(String bar) {
	this.bar = bar;
})))))) (:title Change modifiers to final where possible :command java.apply.workspaceEdit :arguments ((:changes nil :documentChanges ((:textDocument (:version :null :uri file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java) :edits ((:range (:start (:line 11 :character 4) :end (:line 38 :character 25)) :newText final String me = "foo";

    return "Hello World!";

  }

  sealed interface Option {
    record Name(String name) implements Option {
    }
  }

  String bar;

  static Set<Option> parseOptions(final String[] args) {
    final var foo = new Object();
    for (final String arg : args) {

      arg.chars().map(null);
    }
    return null;
  }

  public static void main(final String[] args) {
    System.out.println(args.length);
    // System.out.println(new App().getGreeting(1, 2));
  }

  public static void foo(final ))))))) (:title Sort Members for 'App.java' :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 9 :character 2) :end (:line 40 :character 3)) :newText sealed interface Option {
    record Name(String name) implements Option {
    }
  }

  public static void main(String[] args) {
    System.out.println(args.length);
    // System.out.println(new App().getGreeting(1, 2));
  }

  public static void foo(String bar) {
    System.out.print(bar);
  }

  static Set<Option> parseOptions(String[] args) {
    var foo = new Object();
    for (String arg : args) {

      arg.chars().map(null);
    }
    return null;
  }

  String bar;

  public String getGreeting() {

    String me = "foo";

    return "Hello World!";

  })))))))


* TODO use original xref
currently xref is modified[[ file:lsp-rocks-xref.el]] and it breaks better to have a workaround

xref is defined by some generic method

implementation declare of their backend and set it in xref-backend-functions 
* actions

((:title Change signature for 'parseOptions' :command java.action.applyRefactoringCommand :arguments (changeSignature (:textDocument (:uri file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java) :range (:start (:line 24 :character 30) :end (:line 24 :character 30)) :context (:diagnostics nil)) (:methodIdentifier =app/src\/main\/java=/gradle_scope=/main=/=/gradle_used_by_scope=/main,test=/<javapg{App.java[App~parseOptions~\[QString; :modifier  :returnType Set<Option> :methodName parseOptions :parameters ((:type String[] :name args :defaultValue  :originalIndex 0)) :exceptions nil))) (:title Inline Method :command java.apply.workspaceEdit :arguments ((:changes nil :documentChanges ((:textDocument (:version :null :uri file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java) :edits ((:range (:start (:line 24 :character 2) :end (:line 33 :character 2)) :newText ))))))) (:title Add Javadoc for 'parseOptions' :command java.apply.workspaceEdit :arguments ((:changes nil :documentChanges ((:textDocument (:version :null :uri file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java) :edits ((:range (:start (:line 24 :character 2) :end (:line 24 :character 2)) :newText /**
 * @param args
 * @return
 */
))))))) (:title Organize imports :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 5 :character 0) :end (:line 8 :character 38)) :newText import java.util.Set;)))))) (:title Generate Getters and Setters :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 33 :character 2) :end (:line 33 :character 2)) :newText public String getBar() {
	return bar;
}

public void setBar(String bar) {
	this.bar = bar;
}

)))))) (:title Generate Getters :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 33 :character 2) :end (:line 33 :character 2)) :newText public String getBar() {
	return bar;
}

)))))) (:title Generate Setters :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 33 :character 2) :end (:line 33 :character 2)) :newText public void setBar(String bar) {
	this.bar = bar;
}

)))))) (:title Change modifiers to final where possible :command java.apply.workspaceEdit :arguments ((:changes nil :documentChanges ((:textDocument (:version :null :uri file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java) :edits ((:range (:start (:line 12 :character 4) :end (:line 39 :character 25)) :newText final String me = "foo";

    return "Hello World!";
  }

  sealed interface Option {
    record Name(String name) implements Option {
    }
  }

  String bar;

  static Set<Option> parseOptions(final String[] args) {
    final var foo = new Object();
    for (final String arg : args) {

      arg.chars().map(null);
    }
    return null;
  }

  public static void main(final String[] args) {
    System.out.println(args.length);

    // System.out.println(new App().getGreeting(1, 2));
  }

  public static void foo(final ))))))) (:title Sort Members for 'App.java' :command java.apply.workspaceEdit :arguments ((:changes (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java ((:range (:start (:line 11 :character 2) :end (:line 41 :character 3)) :newText sealed interface Option {
    record Name(String name) implements Option {
    }
  }

  public static void main(String[] args) {
    System.out.println(args.length);

    // System.out.println(new App().getGreeting(1, 2));
  }

  public static void foo(String bar) {
    System.out.print(bar);
  }

  static Set<Option> parseOptions(String[] args) {
    var foo = new Object();
    for (String arg : args) {

      arg.chars().map(null);
    }
    return null;
  }

  String bar;

  public String getGreeting() {
    String me = "foo";

    return "Hello World!";
  })))))))
* actions
;; Command
(:title Generate Getters and Setters :command java.apply.workspaceEdit
        :arguments ((:changes
                     (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java
                      ((:range
                        (:start (:line 33 :character 2) :end
                                (:line 33 :character 2))
                        :newText public String getBar() {
	return bar;
}

public void setBar(String bar) {
	this.bar = bar;
}

))))))
(:title Generate Getters :command java.apply.workspaceEdit :arguments ((:changes
                                                                        (:file:///home/thanh/git/javapg/app/src/main/java/javapg/App.java
                                                                         ((:range
                                                                           (:start
                                                                            (:line
                                                                             33
                                                                             :character
                                                                             2)
                                                                            :end
                                                                            (:line
                                                                             33
                                                                             :character
                                                                             2))
                                                                           :newText
                                                                           public
                                                                           String
                                                                           getBar()
                                                                           {
	return bar;
}

))))))
* completion
error occured:

(wrong-type-argument listp [(:label client :kind 6 :data (:workspacePath /home/thanh/git/lsp-rocks :filePath /home/thanh/git/lsp-rocks/foo.py :position (:line 66 :character 10) :symbolLabel client) :sortText 05.0000.client :documentation (:kind markdown :value ```python
client: LSPClient
```))])


[(:label client :kind 6 :data
         (:workspacePath /home/thanh/git/lsp-rocks :filePath
                         /home/thanh/git/lsp-rocks/foo.py :position
                         (:line 66 :character 10) :symbolLabel client)
         :sortText 05.0000.client :documentation (:kind markdown :value
                                                        ```python
client: LSPClient
```))]

* code action error
[Error  - 7:03:37 a.m.] Sending request workspace/executeCommand failed.
ResponseError: No delegateCommandHandler for java.apply.workspaceEdit
    at handleResponse (/home/thanh/git/lsp-rocks/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
    at handleMessage (/home/thanh/git/lsp-rocks/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
    at processMessageQueue (/home/thanh/git/lsp-rocks/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/home/thanh/git/lsp-rocks/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:491:21) {
  code: -32601,
  data: undefined
}
